# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mercado-pago-config
data:
  MERCADO_PAGO_URL: "https://api.mercadopago.com/"
  URL_NOTIFICACAO: "https://www.yourserver.com/notifications"
---
# Define a 'Service' To Expose the application internally
apiVersion: v1
kind: Service
metadata:
  name: fiap-lanchonete
spec:
  ports:
    # - protocol: "TCP"
    - port: 8080 # Port inside the cluster
      targetPort: 8080 # Port exposed to the outside
  selector:
    app: fiap-lanchonete
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-lanchonete
spec:
  selector:
    matchLabels:
      app: fiap-lanchonete
  replicas: 1
  template:
    metadata:
      labels:
        app: fiap-lanchonete
    spec:
      containers:
        - name: fiap-lanchonete
          image: lamarcke/fiap-lanchonete:1.0.2.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mercado-pago-config
            - secretRef:
                name: mysql-secret
            - secretRef:
                name: mercado-pago-secret
          env:
            - name: DB_URL
              # 'mysql' se refere ao host especificado no service do mysql
              value: "mysql:3306"
---

