name: My Target Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN :
        required: true
      AWS_REGION:
        required: true

env:
  TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
  TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws_token_key: ${{ secrets.AWS_SESSION_TOKEN }} | base64 --decode
  TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
  TF_VAR_db_url: ${{ secrets.DB_URL }}
  TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  TF_VAR_mercado_pago_api_key: ${{ secrets.MERCADO_PAGO_API_KEY }}

permissions:
  contents: read
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform apply
        uses: dflook/terraform-apply@v1