name: My Target Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN :
        required: true
      AWS_REGION:
        required: true

env:
  TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
  TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws_token_key: ${{ secrets.AWS_SESSION_TOKEN }}
  TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
  TF_VAR_db_url: ${{ secrets.DB_URL }}
  TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  TF_VAR_mercado_pago_api_key: ${{ secrets.MERCADO_PAGO_API_KEY }}

permissions:
  contents: read
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform plan
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: fiap-9soat/fiap-lanchonete-infra
          token: ${{ secrets.PAT }}
          clean: true
      
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.1

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false