name: Trigger Target Workflow

on:
  workflow_dispatch:

env:
  TF_ACTION_WORKING_DIR: "terraform"

jobs:
  trigger-job:
    runs-on: ubuntu-latest
    steps:
      - name: Perform trigger steps
        run: echo "Trigger job is setting things up!"

  call-lanchonete-auth:
    needs: trigger-job
    uses: fiap-9soat/fiap-lanchonete-auth/.github/workflows/target-workflow.yml@main
    with:
      message: "Hello from the main workflow!"
    # secrets: inherit
    # secrets: 
    #   AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    #   AWS_REGION:  ${{ secrets.AWS_REGION }}

  call-lanchonete-infra:
    needs: call-lanchonete-auth
    uses: fiap-9soat/fiap-lanchonete-infra/.github/workflows/target-workflow.yml@develop
    with:
      message: "Hello from the main workflow!"
    secrets: inherit

#   call-lanchonete-api:
#     needs: call-lanchonete-infra
#     # needs: [trigger-job, terraform-main]
#     uses: fiap-9soat/fiap-lanchonete/.github/workflows/target-workflow.yml@dev
#     with:
#       message: "Hello from the main workflow!"
#     secrets: inherit

  call-lanchonete-db:
    needs: call-lanchonete-api
    uses: fiap-9soat/fiap-lanchonete-db/.github/workflows/target-workflow.yml@develop
    with:
      message: "Hello from the main workflow!"
    secrets: inherit
