name: Trigger Target Workflow

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: "Input a service name (e.g., demo-app)"
        required: true
      target_version:
        description: "Input a version (e.g., v1.0.0)"
        required: true

jobs:
  trigger-job:
    runs-on: ubuntu-latest
    steps:
    - name: Perform trigger steps
      run: echo "Trigger job is setting things up!"

  call-lanchonete-api:
    needs: trigger-job
    uses: daftK/fiap-lanchonete/.github/workflows/target-workflow.yml@develop
    with:
        message: "Hello from the main workflow!
    secrets: inherit
#   call-lanchonete-db:
#     uses: fiap-9soat/fiap-lanchonete/.github/workflows/target-workflow.yml@develop
#     with:
#       message: "Hello from the main workflow!
#     secrets: inherit
# jobs:
#   trigger:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Trigger Workflow in Another Repository
#         uses: peter-evans/repository-dispatch@v1
#         with:
#           token: ${{ secrets.PAT }}
#           repository: fiap-9soat/fiap-lanchonete-db
#           event-type: my-event
#           aws_access_key: "${{ secrets.AWS_ACCESS_KEY }}"
#           aws_secret_key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
#           aws_token_key: "${{ secrets.AWS_SESSION_TOKEN }}"
#           aws_region: ${{ secrets.AWS_REGION }}
#           eks_cluster_name: "${{ secrets.EKS_CLUSTER_NAME }}"
#         #   client-payload: '{"github_token": "${{ secrets.PAT }}", "aws_access_key": "${{ secrets.AWS_ACCESS_KEY }}", "aws_secret_key": "${{ secrets.AWS_SECRET_ACCESS_KEY }}", "aws_token_key": "${{ secrets.AWS_SESSION_TOKEN }}", "aws_region": "${{ secrets.AWS_REGION }}", "eks_cluster_name": "${{ secrets.EKS_CLUSTER_NAME }}"}'
#       - run: |
#           # Set the required variables
#           repo_owner="daftK"
#           repo_name="fiap-lanchonete"
#           event_type="trigger-workflow"
#           service="${{ github.event.inputs.target_service }}"
#           version="${{ github.event.inputs.target_version }}"

#           curl -L \
#             -X POST \
#             -H "Accept: application/vnd.github+json" \
#             -H "Authorization: Bearer ${{ secrets.PAT }}" \
#             -H "X-GitHub-Api-Version: 2022-11-28" \
#             https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
#             -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"
