name: Trigger Target Workflow

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: "Input a service name (e.g., demo-app)"
        required: true
      target_version:
        description: "Input a version (e.g., v1.0.0)"
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}
  TF_ACTION_WORKING_DIR: "terraform"
  aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
  aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  aws_token_key: ${{ secrets.AWS_SESSION_TOKEN }} | base64 --decode
  aws_region: ${{ secrets.AWS_REGION }}
  db_url: ${{ secrets.DB_URL }}
  db_username: ${{ secrets.DB_USERNAME }}
  db_password: ${{ secrets.DB_PASSWORD }}
  mercado_pago_api_key: ${{ secrets.MERCADO_PAGO_API_KEY }}

jobs:
  trigger-job:
    runs-on: ubuntu-latest
    steps:
      - name: Perform trigger steps
        run: echo "Trigger job is setting things up!"

  terraform-main:
    name: "Terraform Infrastructure Change Management"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: .

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.1

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

#   call-lanchonete-api:
#     needs: trigger-job
#     # needs: [trigger-job, terraform-main]
#     uses: fiap-9soat/fiap-lanchonete/.github/workflows/target-workflow.yml@dev
#     with:
#       message: "Hello from the main workflow!"
#     secrets: inherit

  call-lanchonete-db:
    needs: terraform-main
    uses: fiap-9soat/fiap-lanchonete-db/.github/workflows/target-workflow.yml@develop
    with:
      message: "Hello from the main workflow!"
    secrets: inherit
