name: Trigger Target Workflow

on:
  workflow_dispatch:

env:
  TF_ACTION_WORKING_DIR: "terraform"

jobs:
  trigger-job:
    runs-on: ubuntu-latest
    steps:
      - name: Perform trigger steps
        run: echo "Trigger job is setting things up!"

  #   call-lanchonete-auth:
  #     needs: trigger-job
  #     uses: fiap-9soat/fiap-lanchonete-auth/.github/workflows/target-workflow.yml@main
  #     with:
  #       message: "Hello from the main workflow!"
  #     secrets: inherit

  #   call-lanchonete-infra:
  #     needs: call-lanchonete-auth
  #     uses: fiap-9soat/fiap-lanchonete-infra/.github/workflows/target-workflow.yml@develop
  #     with:
  #       message: "Hello from the main workflow!"
  #       db_url: "mysql:3306"
  #     secrets: inherit

  call-lanchonete-db:
    # needs: call-lanchonete-infra
    uses: fiap-9soat/fiap-lanchonete-db/.github/workflows/target-workflow.yml@develop
    with:
      message: "Hello from the main workflow!"
    secrets: inherit

  call-lanchonete-infra-2:
    needs: call-lanchonete-db
    uses: fiap-9soat/fiap-lanchonete-infra/.github/workflows/target-workflow.yml@develop
    with:
      message: "Hello from the main workflow!"
      db_url: echo ${{ needs.call-lanchonete-db.outputs.db_url }}
    secrets: inherit
